theme: jekyll-theme-slate
title: Welcome to my portfolio!
description: These are some personal projects that I've worked on or am currently working on. Topics include data science, machine learning, efficiency, or really anything that interests me. Enjoy!
