theme: jekyll-theme-slate
title: Welcome to my page!
description: These are some of my personal projects, things that I found interesting and wanted to explore. Enjoy!

Topics include data science, machine learning, operations research, efficiency;
